# Render Deployment Configuration
# https://render.com

services:
  - type: web
    name: myerp-backend
    runtime: node
    plan: starter
    region: singapore
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    
  - type: static
    name: myerp-frontend
    plan: starter
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    pullRequestPreviewsEnabled: false
    
# Auto-deploy from main branch
branches:
  - main
